server:
  port: 8580

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: 2354567007

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  cloud:
    gateway:

      default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
          corsConfigurations:
            '[/**]':
              #allowCredentials: true
              allowedOrigins: "http://localhost:4200"
              allowedHeaders: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - OPTIONS

      routes:
        - id: service_favouritePlayer
          uri: http://localhost:6969
          predicates:
            - Path=/favouritePlayers/**
          filters:
            - AuthenticateFilterFactory
